service: aws-lambda-tut

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  timeout: 15
  stage: production
  region: eu-west-1

functions:
  api:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY